###
GET http://localhost:8080/api/nest-boxes

###
POST http://localhost:8080/api/nest-boxes

###
DELETE http://localhost:8080/api/nest-boxes

###
PUT http://localhost:8080/api/nest-boxes/expiration

###
GET http://localhost:8080/api/nest-boxes/isLiving

###
GET http://localhost:8080/api/nest-boxes/{{nestBoxId}}

###
PUT http://localhost:8080/api/nest-boxes/{{nestBoxId}}

###
DELETE http://localhost:8080/api/nest-boxes/{{nestBoxId}}