POST http://localhost:8080/api/nests
Accept: application/json
Content-Type: application/json

{
  "nestBoxNumber": "1578/c",
  "dateOfSurvey": "2019-06-18",
  "species": "Coracias garrulus",
  "numberOfNestlings": 4,
  "observer": "John Doe"
}

###
POST http://localhost:8080/api/nests
Accept: application/json
Content-Type: application/json

{
"nestBoxNumber": "1600",
"dateOfSurvey": "2015-06-18",
"species": "Corvus monedula",
"numberOfNestlings": 4,
"observer": "John Doe"
}

###
GET http://localhost:8080/api/nests?nest-box-number=1485
Accept: application/json

###
GET http://localhost:8080/api/nests?nest-box-number=1485&species=Coracias%20garrulus
Accept: application/json

###
GET http://localhost:8080/api/nests?species=Corvus%20monedula
Accept: application/json

###
GET http://localhost:8080/api/nests
Accept: application/json

###
GET http://localhost:8080/api/nests/zoology-data
Accept: application/json